// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Vd7r5rgBMNXmn69ZHgBouLn_AbzyHeU',
    appId: '1:249602528732:web:75a21fc4d287150966eb19',
    messagingSenderId: '249602528732',
    projectId: 'pikachueducation-f7dae',
    authDomain: 'pikachueducation-f7dae.firebaseapp.com',
    databaseURL: 'https://pikachueducation-f7dae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pikachueducation-f7dae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClaOeXHSuQWa_fVF2brNJLArnvwFA_cEc',
    appId: '1:249602528732:android:a44b67c5526ef16f66eb19',
    messagingSenderId: '249602528732',
    projectId: 'pikachueducation-f7dae',
    databaseURL: 'https://pikachueducation-f7dae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pikachueducation-f7dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7fzyus5bRifMEWAgMsUU97ohFIYjt8e8',
    appId: '1:249602528732:ios:74035c43033f8aef66eb19',
    messagingSenderId: '249602528732',
    projectId: 'pikachueducation-f7dae',
    databaseURL: 'https://pikachueducation-f7dae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pikachueducation-f7dae.appspot.com',
    iosClientId: '249602528732-0j4nsn1rbg0dvv2epirepq3svo6lbkjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pikachuEducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7fzyus5bRifMEWAgMsUU97ohFIYjt8e8',
    appId: '1:249602528732:ios:6beab7d01489d25066eb19',
    messagingSenderId: '249602528732',
    projectId: 'pikachueducation-f7dae',
    databaseURL: 'https://pikachueducation-f7dae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pikachueducation-f7dae.appspot.com',
    iosClientId: '249602528732-enb6fjnhrj0id927fthhc9e88j4be6b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pikachuEducation.RunnerTests',
  );
}
